# Generated by Django 3.2.5 on 2021-07-08 21:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Items',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_image', models.ImageField(null=True, upload_to='')),
                ('item_name', models.CharField(max_length=100)),
                ('item_qty', models.IntegerField(default=0)),
                ('item_entry_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date_of_order', models.DateTimeField(auto_now_add=True)),
                ('dispached', models.BooleanField(default=False)),
                ('Item_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.items')),
            ],
        ),
    ]
