# Generated by Django 3.2.5 on 2021-07-08 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='items',
            name='item_image',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
